name: deepconvlstm
dataset_name: wear
has_null: true
anno_json:
- data/wear/annotations/6Hz/loso_sbj_0.json
- data/wear/annotations/6Hz/loso_sbj_1.json
- data/wear/annotations/6Hz/loso_sbj_2.json
- data/wear/annotations/6Hz/loso_sbj_3.json
- data/wear/annotations/6Hz/loso_sbj_4.json
- data/wear/annotations/6Hz/loso_sbj_5.json
- data/wear/annotations/6Hz/loso_sbj_6.json
- data/wear/annotations/6Hz/loso_sbj_7.json
- data/wear/annotations/6Hz/loso_sbj_8.json
- data/wear/annotations/6Hz/loso_sbj_9.json
- data/wear/annotations/6Hz/loso_sbj_10.json
- data/wear/annotations/6Hz/loso_sbj_11.json
- data/wear/annotations/6Hz/loso_sbj_12.json
- data/wear/annotations/6Hz/loso_sbj_13.json
- data/wear/annotations/6Hz/loso_sbj_14.json
- data/wear/annotations/6Hz/loso_sbj_15.json
- data/wear/annotations/6Hz/loso_sbj_16.json
- data/wear/annotations/6Hz/loso_sbj_17.json
- data/wear/annotations/6Hz/loso_sbj_18.json
- data/wear/annotations/6Hz/loso_sbj_19.json
- data/wear/annotations/6Hz/loso_sbj_20.json
- data/wear/annotations/6Hz/loso_sbj_21.json
dataset:
  sens_folder: data/wear/6hz
  input_dim: 12
  sampling_rate: 6
  num_classes: 18
  window_size: 6
  window_overlap: 50
  tiou_thresholds:
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
model:
  conv_kernels: 64
  conv_kernel_size: 2
  lstm_units: 128
  lstm_layers: 1
  dropout: 0.5
  conv_type: standard
  temporal_head: lstm
  multirate_training: false
  supported_sample_rates:
  - 6
  - 12
  - 25
  - 50
train_cfg:
  lr: 0.0001
  lr_decay: 0.9
  lr_step: 10
  epochs: 30
  weight_decay: 1.0e-06
  weight_init: xavier_normal
  weighted_loss: true
  log_subdir: deepconvlstm/wear/6hz
loader:
  train_batch_size: 256
  test_batch_size: 64
