name: purecnn
dataset_name: rwhar
has_null: false
anno_json:
- data/realworld/annotations/50hz/waist_accel/loso_sbj_0.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_1.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_2.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_3.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_4.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_5.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_6.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_7.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_8.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_9.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_10.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_11.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_12.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_13.json
- data/realworld/annotations/50hz/waist_accel/loso_sbj_14.json
dataset:
  sens_folder: data/rwhar/25hz
  input_dim: 3
  sampling_rate: 25
  num_classes: 8
  window_size: 25
  window_overlap: 50
  tiou_thresholds:
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
model:
  conv_kernels: 64
  conv_kernel_size: 5
  lstm_units: 128
  lstm_layers: 1
  dropout: 0.5
  conv_type: standard
  supported_sample_rates:
  - 6
  - 12
  - 25
  - 50
  multirate_training: false
  temporal_head: cnn
  kernel_size: 5
train_cfg:
  lr: 0.0001
  lr_decay: 0.9
  lr_step: 10
  epochs: 30
  weight_decay: 1.0e-06
  weight_init: xavier_normal
  weighted_loss: true
  log_subdir: purecnn/rwhar/25hz
  auto_resume: false
loader:
  train_batch_size: 256
  test_batch_size: 64
